app <- ShinyDriver$new("../../", seed = 1234, loadTimeout = 1e+05)
app$snapshotInit("snapshot-test")

app$setInputs(demo1 = "click")
app$setInputs(submit = "click")
app$setInputs(sidebar = "stringdb")
app$setInputs(runstringdb_button = "click")
app$snapshot()
app$setInputs(sidebar = "msigdb")
app$setInputs(runmsigdb_button = "click")
app$snapshot()
app$setInputs(sidebar = "reactome")
app$setInputs(runreactome_button = "click")
app$snapshot()
app$setInputs(sidebar = "david")
app$setInputs(sidebar = "dose")
app$setInputs(rundose_button = "click")
app$snapshot()
app$setInputs(sidebar = "ncg")
app$setInputs(runncg_button = "click")
app$snapshot()
app$setInputs(sidebar = "dgn")
app$setInputs(rundgn_button = "click")
app$snapshot()
app$setInputs(sidebar = "enrichr")
app$setInputs(enrichr_db = "Genome_Browser_PWMs")
app$setInputs(enrichr_db = c("Genome_Browser_PWMs", "TRANSFAC_and_JASPAR_PWMs"))
app$setInputs(enrichr_db = c("Genome_Browser_PWMs", "TRANSFAC_and_JASPAR_PWMs", "Transcription_Factor_PPIs"))
app$setInputs(runenrichr_button = "click")
app$snapshot()
